### PR TITLE
update wechaty&wechaty-puppet dependency  

### PR DESCRIPTION
**Pull request by wj-Mcat**
- update dependency version  
- publish

### CODE REVIEW

**Comment by wj-Mcat** [comment]
`official-account` will send message to actual user,  and this will be avaiable in [48 hours](https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html). So, `sendCustomMessage` will not pass the test if the specific user don't send message to oa in 48 hours. 

> I have never pass the test with command `npm test`.

So, I think we can disable this test feature.

**Comment by huan** [comment]
Yes, I agree that we can disable it for now temporary.

In the future, I believe we should split the unit tests into 3 categories:

1. the 1st class category includes all the unit tests which can run locally, does not need to interactive with any real services.
1. the 2nd class category includes all the unit tests which need to interactive with real services. They should be only enabled when the related environment variables is set.
1. the 3rd class category includes all the unit tests which only can be run with a specific condition, like the `sendCustomMessage`.

Please go ahead to submit PR with the code you need.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
I have fixed the `ci-info` package by installing it from the GitHub.

Please feel free to help yourself to merge this PR when you believe it's ready to go, Cheers!

**Pull request merged**
